### ISSUE TITLE
Seleccionar las funcionalidades iniciales a desarrollar

### ISSUE THREAD

**Issue by mmasias** [mmasias/pyReposU#2]

**Comment by mmasias** [comment]
Preparar documento de lista de funcionalidades

**Comment by mmasias** [comment]
> Preparar documento de lista de funcionalidades

Requiere identificar los casos de uso

**Comment by juanjoc711** [comment]
Elaboración de una lista de funcionalidades iniciales a desarrollar terminada e identificación de actores y casos de uso.

**Comment by juanjoc711** [comment]
Buenas @mmasias.

Quería comentarte que estos días no he avanzado mucho en el proyecto por un exámen que tenía ayer, pero que hoy ya lo retomo para finalizar el estado del arte tal y como dijimos antes del 17.

Por otra parte también le daré otra vuelta a los actores y casos de uso y a las funcionalidades a desarrollar y si te parece la semana que viene lo vemos de nuevo juntos.

Un saludo.

**Comment by mmasias** [comment]
Don't worry: lo primero salir bien en los exámenes.
-
Manuel Masías
http://es.linkedin.com/in/mmasias

**Comment by juanjoc711** [comment]
Actualizadala lista de funcionalidades a desarrollar.

Actualizado el documento conlos actores y casos de uso con nuevos casos de uso

**Comment by mmasias** [comment]
Great! Si quieres nos juntamos mañana para darle forma al avance de esta
semana. Estaré de 5 a 7 en la ofi (además de por la mañana hasta las 3)
-
Manuel Masías
http://es.linkedin.com/in/mmasias

**Comment by juanjoc711** [comment]
Vale genial, mañana sobre las 17:45 que salgo de clase paso por tu despacho entonces,

Un saludo
