### ISSUE TITLE
Documentación de los repos de años anteriores.

### ISSUE THREAD

**Issue by juanjoc711** [mmasias/pyReposU#5]
Buenas @mmasias, te escribía porque estaba comenzando a ver los repositorios de años pasados en "https://github.com/mmasias/mmasias/blob/main/UNEATLANTICO/README.md?plain=1", y el enlace del de ids22-23 no lleva a ningún repo. Quizás es porque ahí aún no llevabas tú la asignatura, o porque está en otro lado pero lo cierto es que no lo encuentro en tu perfil. Ya me comentas si lo tienes oculto o algo, muchas gracias.

**Comment by juanjoc711** [comment]
Perdona, el que no va es el de dsi del año 22-23, ese es el que da 404 not found, que me confundí.

**Comment by juanjoc711** [comment]
Perdona @mmasias , el que no va es el de dsi del año 22-23, ese es el que da 404 not found, que me confundí.

**Comment by mmasias** [comment]
Ahh, ese año no dicté DSI. Y, de todos modos, veámoslo con pinzas porque
esa asignatura tiene alumnos de otros grados, por lo que es atípica

-
Manuel Masías
http://es.linkedin.com/in/mmasias

**Comment by juanjoc711** [comment]
Buenas, por si en algún momento le quieres ir echando un ojo aunque aún no está terminado, la tarea actual de documentación de cómo usaste github en las asignaturas anteriores no la estoy llevando a cabo en las carpetas del repo sino que la estoy elaborando en el apartado wiki de este repo para así aprender su uso ya que no lo conocía hasta que me lo mostraste y así lo aprendo a usar.

**Comment by mmasias** [comment]
De acuerdo! Lo guay es que el wiki lo puedes clonar y trabajar aparte: es
la contraparte documental que va de la mano con el propósito eminentemente
de desarrollo de un repo. Personalmente no lo he usado de esa manera, más
que nada porque cuando inicio una nueva edición de la asignatura se
quedaría (el wiki) en la versión anterior.
-
Manuel Masías
http://es.linkedin.com/in/mmasias

**Comment by juanjoc711** [comment]
Buenas @mmasias  quieres que nos reunamos esta tarde tipo 17:15 como otras semanas y te cuento los avances, para esa hora ya tendré terminado lo que habíamos puesto para estas dos semanas.

Un saludo.

**Comment by mmasias** [comment]
Perfecto!
-
Manuel Masías
http://es.linkedin.com/in/mmasias
