### ISSUE TITLE
GitHub Contributions Tracker

### ISSUE THREAD

**Issue by juanjoc711** [mmasias/pyReposU#6]
Buenas @mmasias , te escribía por si te parece que mañana o cuando prefieras en la semana nos reunamos y te planteo las diferentes propuestas que estuve pensando de métricas que se podrían evaluar en github y distintas opciones para trackear el progreso de los alumnos a través de sus commits para ver cuáles te gustan más.

Un saludo.

**Comment by mmasias** [comment]
¿Qué tal el jueves por la tarde, sobre las 15:30h?

**Comment by juanjoc711** [comment]
Genial, ahí nos vemos entonces.

**Comment by mmasias** [comment]
> Genial, ahí nos vemos entonces.

Crea una cita, así no tengo pretexto para que se me pase 😛
